definitions:
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
      includedFiles: ['*.css', '*.eot', '*.ftl', '*.gif', '*.html', '*.ico', '*.jpeg',
        '*.jpg', '*.js', '*.json', '*.map', '*.otf', '*.png', '*.svg', '*.ttf', '*.woff',
        '*.xml', '*.properties', '*.txt', '*.woff2', '*.hbs']
    /hippo:configuration/hippo:domains/hippofolders/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [sitewriters]
    /hippo:configuration/hippo:domains/preview-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [previewusers]
    /hippo:configuration/hippo:domains/live-documents/readonly:
      hipposys:groups:
        operation: add
        type: string
        value: [liveusers]
