definitions:
  config:
    /hippo:configuration/hippo:modules/webfiles/hippo:moduleconfig:
      watchedModules: [repository-data/webfiles]
      includedFiles: ['*.css', '*.eot', '*.ftl', '*.gif', '*.html', '*.ico', '*.jpeg',
        '*.jpg', '*.js', '*.json', '*.map', '*.otf', '*.png', '*.svg', '*.ttf', '*.woff',
        '*.xml', '*.properties', '*.txt', '*.woff2', '*.hbs']
