definitions:
  config:
    /hst:hst/hst:configurations/templatingsupportdemo/hst:abstractpages/base:
      jcr:primaryType: hst:component
      hst:template: base-layout
      /menu:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.cms7.essentials.components.EssentialsMenuComponent
        hst:parameternames: [selectedMenu, level, menu]
        hst:parametervalues: ['on', '1', main]
        hst:template: base-top-menu
      /top:
        jcr:primaryType: hst:containercomponentreference
        hst:referencecomponent: base/top
      /footer:
        jcr:primaryType: hst:component
        hst:template: base-footer
        /container:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: base/footer
      /footer-handlebars:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.forge.templating.support.demo.components.DemoDataComponent
        hst:template: base-footer-hb
        /container:
          jcr:primaryType: hst:containercomponentreference
          hst:referencecomponent: base/footer
      /footer-thymeleaf:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.forge.templating.support.demo.components.DemoDataComponent
        hst:template: base-footer-thymeleaf
      /footer-thymeleaf-classpath:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.forge.templating.support.demo.components.DemoDataComponent
        hst:template: base-footer-thymeleaf-classpath
      /footer-thymeleaf-servlet:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.forge.templating.support.demo.components.DemoDataComponent
        hst:template: base-footer-thymeleaf-servlet
      /footer-pebble:
        jcr:primaryType: hst:component
        hst:componentclassname: org.onehippo.forge.templating.support.demo.components.DemoDataComponent
        hst:template: base-footer-pebble
